"""summary_async

Revision ID: f6c34066d19e
Revises: b6e3f8a1c4d2
Create Date: 2026-07-07 22:00:15.813170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6c34066d19e'
down_revision: Union[str, Sequence[str], None] = 'b6e3f8a1c4d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('summaries', sa.Column('title', sa.String(length=200), nullable=True))
    # server_default='pending' garante que linhas pré-existentes recebam um valor
    # válido — o backfill logo abaixo promove as que já tinham content para "done".
    op.add_column(
        'summaries',
        sa.Column('status', sa.String(length=16), nullable=False, server_default='pending'),
    )
    op.add_column('summaries', sa.Column('error', sa.String(length=500), nullable=True))
    op.add_column('summaries', sa.Column('mindmap', sa.Text(), nullable=True))
    op.alter_column('summaries', 'llm_model',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('summaries', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    op.execute("UPDATE summaries SET status = 'done' WHERE content IS NOT NULL")
    op.create_index(op.f('ix_summaries_status'), 'summaries', ['status'], unique=False)
    op.drop_column('summaries', 'kind')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('summaries', sa.Column('kind', sa.VARCHAR(length=16), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_summaries_status'), table_name='summaries')
    op.alter_column('summaries', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('summaries', 'llm_model',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.drop_column('summaries', 'mindmap')
    op.drop_column('summaries', 'error')
    op.drop_column('summaries', 'status')
    op.drop_column('summaries', 'title')
    # ### end Alembic commands ###
